image: python:3.7

variables:
  APT_DEPS: libgmp-dev libmpfr-dev libmpc-dev
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
- apt-get update
- apt-get install -y $APT_DEPS
- pip3 install --upgrade pip
- pip3 install pytest pytest-cov pylint sphinx setuptools_scm
- pip3 install .

test:
  stage: test
  tags:
  - shared
  script:
  - pytest

test_install:
  stage: test
  tags:
  - shared
  before_script:
  - echo "Skipping before_script"
  script:
  - apt-get update
  - apt-get install -y $APT_DEPS
  - pip3 install virtualenv
  - ./install.sh
  - source .venv/bin/activate
  - opcuapen --help

style:
  stage: test
  tags:
  - shared
  script:
  - pylint --exit-zero opcuapen

pages:
  stage: deploy
  tags:
  - shared
  script:
  - sphinx-apidoc --ext-mathjax -eo docs opcuapen
  - cd docs/
  - make html
  - mv _build/html ../public
  artifacts:
    paths:
    - public
    expire_in: 3 days
